### PR TITLE
DEVOPS-2691 - pin ohai < 4.0.0

### PR DESCRIPTION
**Pull request by laneatomic**
https://jira.rallyhealth.com/browse/DEVOPS-2691

### CODE REVIEW

**Comment by laneatomic** [comment]
@toofishes @arnaud036 per CI issues we found during testing rally-auth-cookbook.

**Comment by tylermarshall** [comment]
You don't want to do this here. You want to have the pin in metadata.rb, since this file doesn't transfer across cookbooks.

**Comment by laneatomic** [comment]
@tylermarshall moved to metadata.

**Comment by tylermarshall** [comment]
LGTM

**Pull request merged**
