### PR TITLE
COR-629 - Pinning ohai version to 4.2.3 because the latest version is compatible…

### PR DESCRIPTION
**Pull request by arnaud036**
… with chef 12.7+ only

Error:

```
ohai_plugin[nginx] action create

           ================================================================================
           Error executing action `create` on resource 'ohai_plugin[nginx]'
           ================================================================================

           NameError
           ---------
           No resource, method, or local variable named `desired_plugin_path' for `LWRP resource ohai_plugin from cookbook ohai action provider "nginx"'

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/ohai/resources/plugin.rb:80:in `block in class_from_file'
           /tmp/kitchen/cache/cookbooks/ohai/resources/plugin.rb:131:in `block in after_created'
           /tmp/kitchen/cache/cookbooks/ohai/resources/plugin.rb:130:in `each'
           /tmp/kitchen/cache/cookbooks/ohai/resources/plugin.rb:130:in `after_created'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_builder.rb:106:in `build'
           /tmp/kitchen/cache/cookbooks/nginx/recipes/ohai_plugin.rb:27:in `from_file'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:303:in `block in include_recipe'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `include_recipe'
           /tmp/kitchen/cache/cookbooks/nginx/recipes/package.rb:21:in `from_file'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:303:in `block in include_recipe'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `include_recipe'
           /tmp/kitchen/cache/cookbooks/nginx/recipes/default.rb:22:in `from_file'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:303:in `block in include_recipe'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `include_recipe'
           /tmp/kitchen/cache/cookbooks/rally-airflow/recipes/nginx.rb:11:in `from_file'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/nginx/recipes/ohai_plugin.rb

            27: ohai_plugin 'nginx' do
            28:   source_file 'plugins/nginx.rb.erb'
            29:   resource :template
            30:   notifies :reload, 'ohai[reload_nginx]', :immediately
            31: end
            32:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/nginx/recipes/ohai_plugin.rb:27:in `from_file'

           ohai_plugin("nginx") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :ohai_plugin
             cookbook_name "nginx"
             recipe_name "ohai_plugin"
             source_file "plugins/nginx.rb.erb"
             resource :template
           end

```

cc @tylermarshall @mfbaker @toofishes 

NOTE: We need to consider upgrading Chef soon because we are accumulating tech debt here.

### CODE REVIEW

**Comment by postmillenial** [comment]
Confused- does this version bump cause the error you posted, or resolve it?

**Comment by tylermarshall** [comment]
How does this relate at all to the linked ticket? Not sure why nginx would be pulled in there. And we aren't using chef 12.7+ anywhere to date. That's a whole can we haven't opened with everything else taking place.

**Comment by arnaud036** [comment]
Sorry, for the lack of information. When running test-kitchen (with rally-airflow) where nginx cookbook is used, it provisions chef-zero with the latest ohai cookbook. The latest ohai cookbook is only compatible with Chef 12.7+ resulting in this error. So I pin Ohai to a version that is compatible with chef 12.5.1

**Comment by tylermarshall** [comment]
It shouldn't be pinned in this cookbook if it's for testing only. It should be pinned in the berksfile for rally-airflow: https://github.com/AudaxHealthInc/rally-airflow-cookbook/blob/master/Berksfile

Nobody should be uploading cookbooks by hand to the chef server, so it won't pull in the latest version of ohai unless someone puts it there.

**Comment by arnaud036** [comment]
Ok I going this close this PR. I was pinning it here because a bunch of other cookbooks are going to be affected by this issue.

**Pull request closed without merging**
